FROM oven/bun:1.3.14-alpine

ENV NODE_ENV=production
WORKDIR /app
COPY package.json ./
RUN bun install --production
COPY schema.sql ./
COPY src ./src

USER bun
EXPOSE 3000
CMD ["bun", "run", "start"]
